# This file contains the configuration for row data used in the global planner node.
# Each row consists of a name and a list of GPS points (latitude, longitude) that define the path for navigation.
# active row mtlb j0 row chalu rakhni ho uska index dena hai 0 se start hoga
/**:
  ros__parameters:
    utm_epsg: "EPSG:32616"
    spline_resolution: 500
    publish_rate_hz: 1.0
    path_frame_id: "odom"
    rows:
      row_1:
        name: "Row 1"
        A:          [40.0928065, -88.2360040]
        B:          [40.0928668, -88.2355373]
    active_row: 0
